.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\" HISTORY
.\"
.\" @(#)$RCSfile: libpw.3,v $ $Revision: 3.2.5.2 $ (DEC) $Date: 1994/01/14 23:55:02 $
.\"
.\" (c) Copyright 1991, OPEN SOFTWARE FOUNDATION, INC.
.\" ALL RIGHTS RESERVED
.\" 
.TH libpw 3
.SH NAME
.PP
\*Llibpw\*O, \*LlibPW\*O, \*LProgrammers_Workbench_Library\*O \- Provides functions for compatibility with existing programs
.SH LIBRARY
.PP
\*OProgrammers Workbench Library (\*LlibPW.a\*O)
.SH DESCRIPTION
.PP
.iX "libPW"
.iX "Programmers Workbench Library"
.iX "any function"
.iX "anystr function"
.iX "balbrk function"
.iX "cat function"
.iX "clean_up function"
.iX "curdir function"
.iX "dname function"
.iX "fatal function"
.iX "fdfopen function"
.iX "giveup function"
.iX "imatch function"
.iX "index function"
.iX "lockit function"
.iX "logname function"
.iX "move function"
.iX "patoi function"
.iX "patol function"
.iX "repeat function"
.iX "repl function"
.iX "satoi function"
.iX "setsig function"
.iX "setsig1 function"
.iX "sname function"
.iX "strend function"
.iX "substr function"
.iX "trnslat function"
.iX "unlockit function"
.iX "userdir function"
.iX "userexit function"
.iX "username function"
.iX "verify function"
.iX "xalloc function"
.iX "xcreat function"
.iX "xfree function"
.iX "xfreeall function"
.iX "xlink function"
.iX "xmsg function"
.iX "xopen function"
.iX "xpipe function"
.iX "xunlink function"
.iX "xwrite function"
.iX "zero function"
.iX "zeropad function"
\*OThe \*Llibpw\*O functions are provided for compatibility
with existing programs.  Their use in new programs is not recommended.
.VL
.LI "\*Lany (\*Vcharacter, string\*L)"
\*ODetermines whether \*Vstring\*O
contains \*Vcharacter\*O.
.LI "\*Lanystr (\*Vstring1, string2\*L)"
\*ODetermines the offset
in \*Vstring1\*O of the first character that also occurs in
\*Vstring2\*O.
.LI "\*Lbalbrk (\*Vstring, open, close, end\*L)"
\*ODetermines
the offset in \*Vstring\*O of the first character in the string \*Vend\*O
that occurs outside of a balanced string as defined by \*Vopen\*O
and \*Vclose\*O.
.LI "\*Lcat (\*Vdestination, source1,\ .\ .\ .\ , \*L0)"
Concatenates the \*Vsource\*O strings and copies them to \*Vdestination\*O\&.
.LI "\*Lclean_up ( )"
\*ODefaults the cleanup routine.
.LI "\*Lcurdir (\*Vstring\*L)"
\*OPuts the full pathname of
the current directory in \*Vstring\*O.
.LI "\*Ldname (\*Vp\*L)"
\*ODetermines which directory contains
the file \*Vp\*O.
.LI "\*Lfatal (\*Vmessage\*L)"
\*OGeneral purpose error handler.
.LI "\*Lfdfopen (\*Vfd, mode\*L)"
\*OSame as the \*Lstdio fdopen(\|)\*O
function.
.LI "\*Lgiveup (\*Vdump\*L)"
\*OForces a core dump.
.LI "\*Limatch (\*Vpref, string\*L)"
\*ODetermines if the string \*Vpref\*O
is an initial substring of \*Vstring\*O.
.LI "\*Lindex (\*Vstring1, string2\*L)"
\*ODetermines the offset
of the first occurrence in \*Vstring1\*O of \*Vstring2\*O.
.LI "\*Llockit (\*Vlockfile, count, pid\*L)"
\*OCreates a lock
file.
.LI "\*Llogname ( )\*O"
Returns caller's login name.
.LI "\*Lmove (\*Vstring1, string2, n\*L)"
\*OCopies the first \*Vn\*O
characters of \*Vstring1\*O to \*Vstring2\*O.
.LI "\*Lpatoi (\*Vstring\*L)"
\*OConverts \*Vstring\*O to \*Lint\*Oeger.
.LI "\*Lpatol (\*Vstring\*L)"
\*OConverts \*Vstring\*O to \*Llong\*O\&.
.LI "\*Lrepeat (\*Vdestination, string, n\*L)"
\*OSets \*Vdestination\*O
to \*Vstring\*O repeated \*Vn\*O times.
.LI "\*Lrepl (\*Vstring, old, new\*L)"
\*O Replaces each occurrence
of the character \*Vold\*O in \*Vstring\*O with the character \*Vnew\*O\&.
.LI "\*Lsatoi (\*Vstring, ip\*L)"
\*O Converts \*Vstring\*O
to integer and saves it in *\*Vip\*O.
.LI "\*Lsetsig ( )"
\*OCauses signals to be caught by the \*Lsetsig1(\|)\*O
function.
.LI "\*Lsetsig1 (\*Vsignal\*L)"
\*O General purpose signal handling
routine.
.LI "\*Lsname (\*Vs\*L)"
\*O Gets a pointer to the simple
name of full pathname \*Vs\*O.
.LI "\*Lstrend (\*Vstring\*L)"
\*O Finds the end of \*Vstring\*O.
.LI "\*Lsubstr (\*Vs, destination, origin, length\*L)"
\*OPlaces
a substring of string \*Vs\*O in \*Vdestination\*O using the
offset \*Vorigin\*O and \*Vlength\*O.
.LI "\*Ltrnslat (\*Vs, old, new, destination\*L)"
\*OCopies string \*Vs\*O
into \*Vdestination\*O and replaces any character in \*Vold\*O
with the corresponding characters in \*Vnew\*O.
.LI "\*Lunlockit (\*Vlockfile, pid\*L)"
\*ODeletes the lock file.
.LI "\*Luserdir (\*Vuid\*L)"
\*OGets the user's login directory.
.LI "\*Luserexit (\*Vcode\*L)"
\*ODefaults user exit routine.
.LI "\*Lusername (\*Vuid\*L)"
\*OGets the user's login name.
.LI "\*Lverify (\*Vstring1, string2\*L)"
\*ODetermines the offset
in \*Vstring1\*O of the first character that is not also
in \*Vstring2\*O.
.LI "\*Lxalloc (\*Vasize\*L)"
\*OAllocates memory.
.LI "\*Lxcreat (\*Vname, mode\*L)"
\*OCreates a file.
.LI "\*Lxfree (\*Vaptr\*L)"
\*OFrees memory.
.LI "\*Lxfreeall ( )"
\*O Frees all memory.
.LI "\*Lxlink (\*Vf1, f2\*L)"
\*O Links files.
.LI "\*Lxmsg (\*Vfile, func\*L)"
\*OCalls the \*Lfatal(\|)\*O function
with an appropriate error message.
.LI "\*Lxopen (\*Vname, mode\*L)"
\*OOpens a file.
.LI "\*Lxpipe (\*Vt\*L)"
\*OCreates a pipe.
.LI "\*Lxunlink (\*Vf\*L)"
\*ORemoves a directory entry.
.LI "\*Lxwrite (\*Vfd, buffer, n\*L)"
\*OWrites \*Vn\*O bytes
to the file associated with \*Vfd\*O from \*Vbuffer\*O.
.LI "\*Lzero (\*Vp, n\*L)"
\*OZeros \*Vn\*O bytes starting
at address \*Vp\*O.
.LI "\*Lzeropad (\*Vs\*L)"
\*OReplaces the initial blanks with
the character '0' in string \*Vs\*O.
.iX "Programmers Workbench Library"
.iX "any function"
.iX "anystr function"
.iX "balbrk function"
.iX "cat function"
.iX "clean_up function"
.iX "curdir function"
.iX "dname function"
.iX "fatal function"
.iX "fdfopen function"
.iX "giveup function"
.iX "imatch function"
.iX "index function"
.iX "lockit function"
.iX "logname function"
.iX "move function"
.iX "patoi function"
.iX "patol function"
.iX "repeat function"
.iX "repl function"
.iX "satoi function"
.iX "setsig function"
.iX "setsig1 function"
.iX "sname function"
.iX "strend function"
.iX "substr function"
.iX "trnslat function"
.iX "unlockit function"
.iX "userdir function"
.iX "userexit function"
.iX "username function"
.iX "verify function"
.iX "xalloc function"
.iX "xcreat function"
.iX "xfree function"
.iX "xfreeall function"
.iX "xlink function"
.iX "xmsg function"
.iX "xopen function"
.iX "xpipe function"
.iX "xunlink function"
.iX "xwrite function"
.iX "zero function"
.iX "zeropad function"
.LE
.EQ
delim off
.EN
