.\" This manpage source uses rsml coding. 
.so /usr/share/lib/tmac/sml
.so /usr/share/lib/tmac/rsml
.\"
.\"
.\" *********************************************************************
.\" *                                                                   *
.\" *      Copyright (c) Digital Equipment Corporation, 1991, 1994      *
.\" *                                                                   *
.\" *                       All Rights Reserved.                        *
.\" *                                                                   *
.\" *********************************************************************
.\"
.\"
.\" HISTORY
.\"
.TH dots 4
.SH NAME
.PP
\*Ldots\*O, \*LDOTS\*O \- Data Object Transport Syntax (DOTS) files
.SH DESCRIPTION
.PP
.iX "DOTS"
.iX "Data Object Transport Syntax (DOTS) files"
.iX "file" "Data Object Transport Syntax (DOTS)"
.iX "DDIS/ASN.1 encoding"
DOTS (Data Object Transport Syntax) is a DDIS/ASN.1 syntax for
encapsulating and transferring revisable DDIF compound documents and DTIF files
having external links to multiple subfiles or data objects via mail systems.
When the referenced subfiles or objects are moved from one location to
another, the storage address (for example, file name)
must be updated within the base document.
.PP
DOTS allows composite data objects, such as compound documents with linked
subfiles, to be moved (mailed) from one location to another as a single
object and allows the necessary storage reference to be updated as part
of the process.
.PP
For more information, refer to manpages for the
\*Lctod\*O and \*Ldtoc\*O commands, which are used to pack and unpack
DDIF and DTIF files and their externally linked subfiles.
The commands can also be used to copy a related set
of DDIF or DTIF files, or both, from one location to another.
.SH SEE ALSO
.PP
cdoc(1), ctod(1), dtoc(1), cda(4), ddif(4), ddis(4), dtif(4)
.EQ
delim off
.EN
